### ISSUE TITLE
Causes Error With TerminalPlus

### ISSUE THREAD

**Issue by Gideon2361** [Toliann/Argent#1]
This is the TerminalPlus in question (there are 2 that I know of): https://thunderstore.io/c/lethal-company/p/Slam/TerminalPlus/

When running the "moons" command to show the list of moons, an invalid key exception is thrown and no moons are listed.  This issue only happens with Argent enabled.  Other of your moons that do NOT have this problem include Spectralis and Nyx.

**Comment by Toliann** [comment]
I'll see what's wrong and fix it
